### ISSUE TITLE
Anchor header disabling and Original relative paths support

### ISSUE THREAD

**Issue by DeusDeorum1** [Atlas-Authority/MarkdownMacro#19]
Hello!
We are currently using you plugin and are pretty satisfied with the experience.
And we would like to improve experience even further and have an option to disable header's anchoring and enable support of original relative paths, meaning it would be nice to resolve relative paths as paths of the Team Foundation Server's file explorer paths where we store our .md files.

Do you think it`s possible for you to implement these features? If so, how long would it take?
Or otherwise we can implement the features ourselves. In this case, how long approximately would it take for you to review our PRs?

Best regards

**Comment by bberenberg** [comment]
@DeusDeorum1 thanks for the feedback. I believe that our last release improved the relative path handling, have you tried that? You are welcome to file a PR to add these features. We don't have a formal PR review timeline, but we will try and be quick about it.

**Comment by DeusDeorum1** [comment]
Thanks for the quick reply. I I`ll check if we are using the latest version, thanks for the heads up.
And I have another question regarding these features: how often do you release new versions to the atlassian marketplace?

All in all then I believe we can contribute to your repo and that would be the quickest option.
Thanks

**Comment by bberenberg** [comment]
We release whenever something new is ready. We welcome PR's to this repo for any improvements you want to do. If you want to confirm whether or not something will be accepted ideologically, feel free to make an issue and ask the question before you invest time into doing the dev. The one thing we will likely need to add is some kind of a CLA.

**Comment by bberenberg** [comment]
I have tried to add a CAA bot to this repo, still needs to be verified as working. In the meantime, @DeusDeorum1 do you mind if I close this issue?

**Comment by DeusDeorum1** [comment]
@bberenberg Yeah, sure. I don`t mind. In a weak time or less I believe there will be a couple of PRs regarding these features from me and my colleague

**Comment by bberenberg** [comment]
Great thanks! I look forward to reviewing them.
