### ISSUE TITLE
Fix release pipeline

### ISSUE THREAD

**Issue by bberenberg** [Atlas-Authority/MarkdownMacro#49]
Looks like we need to adjust the branch permissions to work with the automated release setup, or actually adjust the release setup. We want to have protected branches.

https://github.com/Atlas-Authority/MarkdownMacro/runs/4845930963

**Comment by nhan-nguyen-se** [comment]
@bberenberg Can you confirm the protected rules are not applied for admin user?
![image](https://user-images.githubusercontent.com/39516534/149854340-0cce9157-520f-47eb-bcbb-68853bf079db.png)
Include administrators need to be unchecked.

**Comment by bberenberg** [comment]
Correct. I guess we need to make the devops user an admin?

![Google Chrome 2022-01-18 at 11 36 09](https://user-images.githubusercontent.com/4259775/149979087-dc87a810-6708-430e-b64c-3bd9c892f006.png)

**Comment by nhan-nguyen-se** [comment]
No I don't think we need to grant perms for devops email. Can you bypass the user whose PAT is generated from pull request rule? Here is the instructions https://github.blog/changelog/2021-11-19-allow-bypassing-required-pull-requests/

**Comment by bberenberg** [comment]
Yup, I overlooked that option, good catch! Thanks.
