### ISSUE TITLE
Migrate http-request-action to community repo

### ISSUE THREAD

**Issue by nhan-nguyen-se** [Atlas-Authority/MarkdownMacro#60]
We recently fork this repo [fjogeleit/http-request-action](https://github.com/fjogeleit/http-request-action) and add a feature to fit our need. We also PR back to the upstream and it has been [merged](https://github.com/fjogeleit/http-request-action/pull/37) already. So:
1. migrate our release action to use community repo instead so that we don't need to maintain the repo ourself
2. remove forked repo [Atlas-Authority/http-request-action](https://github.com/Atlas-Authority/http-request-action)

@bberenberg I will need your help on item 2 as I don't have perm to delete it.

**Comment by bberenberg** [comment]
https://github.com/Atlas-Authority/http-request-action has been archived in GH
