### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by dasigvr** [Atlas-Authority/MarkdownMacro#68]
Hi guys,

In the marketplace this extension is advertised like this:

> Use inline text, a remote URL, or an attachment to embed Markdown, HTML, PlantUML, LaTeX, Diagrams, AsciiDoc, Graphviz, Mermaid

Is that accurate? I'm not able to visualize my mermaid diagrams and would like to know if and how to enable those extensions.

Screenshot:

![Screenshot](https://user-images.githubusercontent.com/62327440/179956428-4fb5ba44-72bc-4e97-a0a5-ad5029d8f32f.png)

**Comment by boris-moduscreate** [comment]
You can see the differences at https://atlasauthority.atlassian.net/wiki/spaces/MARKDOWNCLOUD/pages/2666233923/Markdown+Macro+for+Confluence+-+Differences+in+Cloud+version

Unfortunately we can't put different text in that section for Server and Cloud. It's a constraint in how Atlassian created the Marketplace UI. Most of that functionality is for Cloud.

**Comment by dasigvr** [comment]
Thanks a lot for the explaination.
