### ISSUE TITLE
new feature adding mermaidjs renderer to MarkdownMacro  and MarkdownFROMURLMacro 

### ISSUE THREAD

**Issue by ateixeirafr** [Atlas-Authority/MarkdownMacro#76]
Hello,
I would like to contribute to MarkdownMacro opensource by adding support for mermaid js 9.1.7 which I just coded for myself use on my local standalone confluence server.
I'm not used to doing this kind of process. So, please explain me how to proceed. Thank you in advance for your assistance.
Regards

**Comment by boris-moduscreate** [comment]
Hello,

Thanks for offering to share your work with the other users of this app. We already support mermaidjs in Cloud so this will be a welcome addition for the on-prem version. I think we would want to ensure we have a smooth migration path alongside merging these changes in. For now, I would recommend that you file a PR to this repo and let us review that, and we can go from there.

CC @khanguyen88 / @nhan-nguyen-se 

Thanks,
Boris
