### ISSUE TITLE
No body when using macro via REST API

### ISSUE THREAD

**Issue by Zujiry** [Atlas-Authority/MarkdownMacro#83]
## Problem  
I want to use the REST / SOAP API of Confluence to use your markdown macro via pythons atlassian library. If I use <ac:macro ac:name="markdown">Random Markdown</ac:macro> or <ac:rich-body-text> / <ac:plain-text-body> no body is found in the resulting confluence page.

### Code
```
cnf.update_or_create(  
    some_number,   
    title,   
    '<ac:macro ac:name="markdown"><ac:plain-text-body># Test</ac:plain-text-body></ac:macro>',   
    representation='storage'  
)
```  
The macro is always empty with no body. How does that work for your macro?

**Comment by boris-moduscreate** [comment]
The easiest way to test this would be to create a page with some dummy text on it, and then use the View Storage Format button:

![Google Chrome 2022-11-21 at 12 28 09](https://user-images.githubusercontent.com/107943674/203121446-f8bf7929-641e-4dd9-9585-a607dfe8c483.png)

For example, in my test page, I have:

```
<ac:structured-macro ac:name="markdown" ac:schema-version="1" ac:macro-id="77fffe98-f000-43a8-b4cf-35f98f635e4e"><ac:plain-text-body><![CDATA[## Test]]></ac:plain-text-body></ac:structured-macro>
```
I don't know off the top of my head how you would generate the macro ID in a new request.

**Comment by Zujiry** [comment]
Thank you very much @boris-moduscreate. The missing CDATA was the problem and your trick will hopefully help me in the future too :)
