### ISSUE TITLE
Confluence Data Center Support

### ISSUE THREAD

**Issue by max1c** [Atlas-Authority/MarkdownMacro#88]
I was trying to use this extension for mermaid but it's not working. Then I saw the following comment: https://marketplace.atlassian.com/apps/1211438/markdown-html-plantuml-latex-diagrams-open-api-mermaid?hosting=datacenter&tab=reviews

>
`Modus Create
The Data Center version doesn't support Mermaid. Mermaid is only supported in the Cloud version, and even then only standalone outside of Markdown content. If you would like to add Mermaid support to the DC version it is open source and we accept pull requests at https://github.com/Atlas-Authority/MarkdownMacro`

Can this be added?

**Comment by boris-moduscreate** [comment]
We don't plan to implement this ourselves, but if you want to implement this and file a PR we would be happy to accept a PR.

**Comment by max1c** [comment]
Can you explain why this is only supported for the Cloud version but not for the Data Center? What is the difference?

**Comment by boris-moduscreate** [comment]
They're completely different codebases and people pay us for the Cloud one and this on-prem one is free. If people want to contribute improvements to the on-prem version we are happy to merge them in where it makes sense.

**Comment by max1c** [comment]
Apparently this works already works on datacenter confluence by using ``` mermaid ``` tags.
